# Generated by Django 3.0.7 on 2020-06-30 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('timestamp', models.DateField(auto_now=True)),
                ('slug', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='-', max_length=100)),
                ('question_file', models.FileField(blank=True, null=True, upload_to='question/documents/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='question/covers/')),
                ('created_at', models.DateTimeField(blank=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_group.CreateGroup')),
            ],
        ),
    ]
